version: '3'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: djangotest
      POSTGRES_USER: djangotest
      POSTGRES_PASSWORD: djangotest
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
